In [1]:
#Classification problem

In [2]:
import numpy as np
import pandas as pd

In [3]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])

In [4]:
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [5]:
y = np.array([0,1,1,1])

In [6]:
w = np.array([1,1])

In [7]:
b = -0.5

In [8]:
pred = []

In [11]:
for a in x:
    y_hat = np.dot(a,w) + b
    pred.append(activation(y_hat))

In [10]:
def activation(z):
    if z>= 0:
        return 1
    else:
        return 0
        

In [13]:
pred

[0, 1, 1, 1]

In [14]:
#perceptron learning


In [15]:
import math

In [17]:
epochs = 100 #no of iterartion

In [18]:
alpha = 0.2

In [22]:
w0 = np.random.random()
w1 = np.random.random()
w2 = np.random.random()

In [24]:
print(f"w0 = {w0},w1 = {w1},w2 =  {w2}")

w0 = 0.25772777463394436,w1 = 0.8398607325965058,w2 =  0.5242928356448937


In [25]:
del_w0 = 1
del_w1 = 1
del_w2 = 1

In [39]:
train_data_temp = ([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
train_data = np.asarray(train_data_temp)
output = np.array([0,1,1,1,1,1,1,1])

In [40]:
train_data

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [31]:
output

array([0, 1, 1, 1, 1, 1, 1, 1])

In [41]:
bias = 0

In [57]:
for i in range(epochs):
    j = 0
    for x in train_data:
        y_hat = w0*x[0] + w1*x[1] + w2*x[2] + bias

        if y_hat >= 0:
            act = 1
        else:
            act = 0
        err =  output[j]- act

        del_w0 = alpha*x[0] * err 
        del_w1 = alpha*x[1] * err
        del_w2 = alpha*x[2] * err

        w0 += del_w0
        w1 += del_w1
        w2 += del_w2

        j += 1
        print("epochs", i+1, "error = ", err)
        print(del_w0,del_w1,del_w2)

print("w0 =", w0, "w1 = ", w1, "w2  = ", w2) 

epochs 1 error =  -1
-0.0 -0.0 -0.0
epochs 1 error =  0
0.0 0.0 0.0
epochs 1 error =  0
0.0 0.0 0.0
epochs 1 error =  0
0.0 0.0 0.0
epochs 1 error =  0
0.0 0.0 0.0
epochs 1 error =  0
0.0 0.0 0.0
epochs 1 error =  0
0.0 0.0 0.0
epochs 1 error =  0
0.0 0.0 0.0
epochs 2 error =  -1
-0.0 -0.0 -0.0
epochs 2 error =  0
0.0 0.0 0.0
epochs 2 error =  0
0.0 0.0 0.0
epochs 2 error =  0
0.0 0.0 0.0
epochs 2 error =  0
0.0 0.0 0.0
epochs 2 error =  0
0.0 0.0 0.0
epochs 2 error =  0
0.0 0.0 0.0
epochs 2 error =  0
0.0 0.0 0.0
epochs 3 error =  -1
-0.0 -0.0 -0.0
epochs 3 error =  0
0.0 0.0 0.0
epochs 3 error =  0
0.0 0.0 0.0
epochs 3 error =  0
0.0 0.0 0.0
epochs 3 error =  0
0.0 0.0 0.0
epochs 3 error =  0
0.0 0.0 0.0
epochs 3 error =  0
0.0 0.0 0.0
epochs 3 error =  0
0.0 0.0 0.0
epochs 4 error =  -1
-0.0 -0.0 -0.0
epochs 4 error =  0
0.0 0.0 0.0
epochs 4 error =  0
0.0 0.0 0.0
epochs 4 error =  0
0.0 0.0 0.0
epochs 4 error =  0
0.0 0.0 0.0
epochs 4 error =  0
0.0 0.0 0.0
epochs 4 error =  0
0.0 

In [58]:
test_data = np.array([1,1,1])