<a href="https://colab.research.google.com/github/Nishchal-ll/Machine-Learning/blob/main/machinelearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Introduction to NumPy*

What we will cover?


*   Creating single dimensional arrays 👌👍
*   Multidimensional arrays
*   Randomly generated arrays
*   Randomly generated arrays
*   Element wise operations
*   Summarizing operations








## Single Dimensional Arrays

In [2]:
import numpy as np
#create an array with all the elements to be zeros


np.zeros(5)


array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
#create array of size 11 with all elements 3
np.full(11, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
np.array([1,2,3,4,5])
# self array

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(3, 10)
# starting with 3 and going till 9 excluding 10

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
#create an array with evenly spaced numbers with specified range
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

#Multi Dimensional Array

In [ ]:
np.zeros((3,4))
# 3 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,2))
#square matrix with all elements 1

array([[1., 1.],
       [1., 1.]])

In [ ]:
# square 3 by 3 matrix with elements staring from 1 to 9  big bracket used

np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# changing 2 to 20 by initializing array to varibale and changing index
array= np.array([[1,2,3],[4,5,6],[7,8,9]])
array[0, 1]=20
print(array)

[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
# changing third row to 1,1,1
array= np.array([
    [1,2,3],
 [4,5,6],
  [7,8,9]
    ])
array[2]=[1,1,1]
print(array)

[[1 2 3]
 [4 5 6]
 [1 1 1]]


In [ ]:
# changing third column to 1,1,2
array= np.array([
    [1,2,3],
 [4,5,6],
  [7,8,9]
    ])
array[:, 2]=2
print(array)

[[1 2 2]
 [4 5 2]
 [7 8 2]]


In [ ]:
# creating 3*3 dimensional array with all elements 10
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

# Randomly generated arrays


- Numpy can create arrays filled with random numbers
- to ensure the reproductibility, you can set a seed using ``` np.random.seed()``` It will generate the exact same random numbers for each executions
-If you remove or change the seed values, the sequence of random numbers will be changed


In [ ]:
np.random.rand(5)


array([0.97439155, 0.75819898, 0.79814318, 0.90653071, 0.22896115])

In [ ]:
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [ ]:
np.random.randn(5,2)

array([[-1.03446493,  0.66424004],
       [-1.13937438, -0.89472205],
       [-0.2207972 , -0.43007258],
       [ 1.19972246,  0.1222967 ],
       [ 0.54794733, -0.52658091]])

In [3]:
np.random.randint( low=0, high=100, size=(6,9))

array([[31, 22, 53, 89, 72, 10, 91, 61, 93],
       [78, 87,  2, 62, 45, 59, 79, 45, 52],
       [50, 78, 24, 69,  6, 65, 57, 78, 99],
       [54, 87, 75, 40, 63, 33, 61, 43, 17],
       [71, 39, 98, 48, 51,  5, 41,  8, 56],
       [52, 43, 80, 40, 45, 93, 80, 50, 22]])

## Element wise operation on entire arrays element by element**

In [4]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [5]:
b=(10+(a*2))
b

array([10, 12, 14, 16, 18])

In [6]:
a

array([0, 1, 2, 3, 4])

In [7]:
a= a*5
a

array([ 0,  5, 10, 15, 20])

In [9]:
a>=2

array([False, False, False, False,  True])

In [11]:
a>b

array([False, False, False, False,  True])

In [12]:
#summarizing of the data
# numpy provides functions for summarizing array data

a.std()

7.0710678118654755

In [13]:
a.min()

0

In [14]:
a.max()

20

In [15]:
a.sum()

50